spring:
  application:
    name: EmployeeManagmentSystem
  datasource:
    url: jdbc:postgresql://localhost:5432/EMS
    username: postgres
    password: tiger
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080